[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sumtui"
version = "0.5.26"
description = "A tiny, portable and retro-flavored TUI toolkit for Python and Rich."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "GPL-2.0-or-later" }
authors = [{ name = "William Martinez Bas", email = "metfar@gmail.com" }]
dependencies = ["rich>=13.0", "pygments>=2.15"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: User Interfaces",
]

[project.scripts]
sumtui = "sumtui.__main__:main"
sumprogress = "sumtui.progress_cli:main"
sumedit = "sumtui.tools.edit:main"
sumeol = "sumtui.tools.eolconv:main"
suminput = "sumtui.tools.input:main"
sumtheme = "sumtui.tools.themeedit:main"
sumdialog = "sumtui.tools.dialog:main"
sumide = "sumtui.tools.ide:main"
sumpyide = "sumtui.tools.ide:main_python"
sumride = "sumtui.tools.ide:main_r"
sumbashide = "sumtui.tools.ide:main_bash"
sumcide = "sumtui.tools.ide:main_c"
sumcppide = "sumtui.tools.ide:main_cpp"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["sumtui*"]
